// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeManager.Api.Data;

#nullable disable

namespace RecipeManager.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251222230134_AddCollectionPreviewImageContent")]
    partial class AddCollectionPreviewImageContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RecipeManager.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FCD34D",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#34D399",
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F87171",
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#F472B6",
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#A78BFA",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#60A5FA",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#FB923C",
                            Name = "Appetizers"
                        });
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreviewImageContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("PreviewImageContentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.CollectionRecipe", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CollectionId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("CollectionRecipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PreviewImageContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("PreviewImageContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#10B981",
                            Name = "Vegetarian",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#059669",
                            Name = "Vegan",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F59E0B",
                            Name = "Gluten-Free",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#8B5CF6",
                            Name = "Dairy-Free",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#EF4444",
                            Name = "Keto",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Color = "#EC4899",
                            Name = "Paleo",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Color = "#3B82F6",
                            Name = "Quick (<30 min)",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6366F1",
                            Name = "Medium (30-60 min)",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Color = "#8B5CF6",
                            Name = "Long (>60 min)",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Color = "#10B981",
                            Name = "Italian",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Color = "#F59E0B",
                            Name = "Mexican",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Color = "#EF4444",
                            Name = "Asian",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Color = "#3B82F6",
                            Name = "American",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Color = "#06B6D4",
                            Name = "Mediterranean",
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Color = "#F97316",
                            Name = "Indian",
                            Type = 2
                        });
                });

            modelBuilder.Entity("RecipeManager.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthSub")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthSub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Collection", b =>
                {
                    b.HasOne("RecipeManager.Api.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.CollectionRecipe", b =>
                {
                    b.HasOne("RecipeManager.Api.Models.Collection", "Collection")
                        .WithMany("CollectionRecipes")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Models.Recipe", "Recipe")
                        .WithMany("CollectionRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Favorite", b =>
                {
                    b.HasOne("RecipeManager.Api.Models.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Recipe", b =>
                {
                    b.HasOne("RecipeManager.Api.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecipeManager.Api.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.RecipeTag", b =>
                {
                    b.HasOne("RecipeManager.Api.Models.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeManager.Api.Models.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Collection", b =>
                {
                    b.Navigation("CollectionRecipes");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Recipe", b =>
                {
                    b.Navigation("CollectionRecipes");

                    b.Navigation("Favorites");

                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("RecipeManager.Api.Models.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Favorites");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
